//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextParser.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Examples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Examples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextParser.Tests.Properties.Examples", typeof(Examples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Text&gt;
        ///  &lt;Sentences&gt;
        ///    &lt;Sentece&gt;
        ///      &lt;Words&gt;
        ///        &lt;Word&gt;a&lt;/Word&gt;
        ///        &lt;Word&gt;had&lt;/Word&gt;
        ///        &lt;Word&gt;lamb&lt;/Word&gt;
        ///        &lt;Word&gt;little&lt;/Word&gt;
        ///        &lt;Word&gt;Mary&lt;/Word&gt;
        ///      &lt;/Words&gt;
        ///    &lt;/Sentece&gt;
        ///    &lt;Sentece&gt;
        ///      &lt;Words&gt;
        ///        &lt;Word&gt;Aesop&lt;/Word&gt;
        ///        &lt;Word&gt;and&lt;/Word&gt;
        ///        &lt;Word&gt;called&lt;/Word&gt;
        ///        &lt;Word&gt;came&lt;/Word&gt;
        ///        &lt;Word&gt;for&lt;/Word&gt;
        ///        &lt;Word&gt;Peter&lt;/Word&gt;
        ///        &lt;Word&gt;the&lt;/Word&gt;
        ///        &lt;Word&gt;wolf&lt;/Word&gt;
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xmlResult {
            get {
                return ResourceManager.GetString("xmlResult", resourceCulture);
            }
        }
    }
}
